version: '3.8'

services:
  web:
    build: .
    command: uvicorn instclone.asgi:application --host 0.0.0.0 --port 8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_prod:/var/lib/postgresql/data/

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./app/static:/static
    depends_on:
      - web
      - db
      - redis

  minio:
    image: minio/minio
    command: server /data --console-address ":9090"
    ports:
      - "9090:9090"
      - "9000:9000"
    environment:
      MINIO_STS_ENABLE: "off"
    env_file:
      - ./.env.prod
    volumes:
      - ./minio:/data

  redis:
    image: bitnami/redis:latest
    hostname: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  worker:
    build: 
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./app:/app
    links:
      - redis
    depends_on:
      - db
    env_file:
      - ./.env.prod

volumes:
  postgres_prod: