# Generated by Django 4.2.6 on 2023-12-07 05:27

from django.db import migrations, models
import userpost.models


class Migration(migrations.Migration):

    dependencies = [
        ('userpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='image',
            field=models.ImageField(storage=userpost.models.PhotoS3Storage(), upload_to=''),
        ),
    ]
