# Generated by Django 4.2.6 on 2023-11-26 14:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userpost', '0001_initial'),
        ('like', '0002_remove_postlike_why'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('user', 'post')},
        ),
    ]
